config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  get 'about', to: 'pages#about'

  resources :trips do
    resources :places
    post 'invite', to: 'trips#invite'
    get 'users', to: 'trips#users'
  end

  get '/memberships/confirm/:id', to: 'memberships#confirm', as: :confirm_membership

  devise_for :users
end

app/models/membership.rb
class Membership < ActiveRecord::Base
  belongs_to :user
  belongs_to :trip
end

app/models/place.rb
class Place < ActiveRecord::Base
  belongs_to :user
  belongs_to :trip

  geocoded_by :address
  after_validation :geocode

  validates :name, presence: true
  validates :address, presence: true
end

app/models/trip.rb
class Trip < ActiveRecord::Base
  belongs_to :user
  has_many :places
  has_many :memberships
  has_many :users, through: :memberships

  validates :name, presence: true
  validates :date, presence: true


  alias_method :owner, :user
  alias_method :owner=, :user=

  def membership(user)
    Membership.find_by(user: user, trip: self)
  end

  def members
    memberships.where(active: true).map(&:user)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :memberships
  has_many :trips, through: :memberships

  validates :email, presence: true, uniqueness: true
  validates :name, presence: true

  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

  def to_s
    name
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include Pundit
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  decent_configuration do
    strategy DecentExposure::StrongParametersStrategy
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end
  
end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  def confirm
    membership = Membership.find(params[:id])
    authorize membership
    membership.update(active: true)
    redirect_to membership.trip
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController

  expose(:trip)
  expose(:places) { trip.places }
  expose(:place, attributes: :place_params)
  expose(:user)

  before_action :authenticate_user!

  # GET /places
  # GET /places.json
  def index
    @hash = Gmaps4rails.build_markers(places) do |place, marker|
      marker.lat place.latitude
      marker.lng place.longitude
      marker.infowindow "<h4>#{place.name}</h4><p>#{place.description}</p>"
    end
    gon.push(hash: @hash)
  end

  # GET /places/1
  # GET /places/1.json
  def show
  end

  # GET /places/new
  def new
  end

  # GET /places/1/edit
  def edit
  end

  # POST /places
  # POST /places.json
  def create
    place = Place.new(place_params)
    place.user = current_user
    place.trip = Trip.find(params[:trip_id])

    respond_to do |format|
      if place.save
        format.html { redirect_to trip_places_path(place.trip, place), notice: 'Place was successfully created.' }
        format.json { render :show, status: :created, location: place }
      else
        format.html { render :new }
        format.json { render json: place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1
  # PATCH/PUT /places/1.json
  def update
    respond_to do |format|
      if place.save
        format.html { redirect_to trip_place_path(place.trip, place), notice: 'Place was successfully updated.' }
        format.json { render :show, status: :ok, location: place }
      else
        format.html { render :edit }
        format.json { render json: place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    place.destroy
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Place was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def place_params
      params.require(:place).permit(:address, :description, :price, :name, :longitude, :latitude)
    end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController

  expose(:trips) { current_user.trips.decorate }
  expose(:trip, attributes: :trip_params)
  expose(:user)

  before_action :set_trip, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def invite
    trip = Trip.find(params[:trip_id])
    authorize trip
    InviteMember.new(
      invite_params[:email],
      invite_params[:name],
      trip.id
    ).call
    redirect_to trip
  end

  # GET /trips
  # GET /trips.json
  def index
  end

  def users
  end

  # GET /trips/1
  # GET /trips/1.json
  def show
    @membership = trip.membership(current_user)
  end

  # GET /trips/new
  def new
  end

  # GET /trips/1/edit
  def edit
  end

  # POST /trips
  # POST /trips.json
  def create
    trip.user = current_user
    trip.users << current_user

    respond_to do |format|
      if trip.save
        format.html { redirect_to trip, notice: 'Trip was successfully created.' }
        format.json { render :show, status: :created, address: trip }
      else
        format.html { render :new }
        format.json { render json: trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trips/1
  # PATCH/PUT /trips/1.json
  def update
    respond_to do |format|
      if trip.update(trip_params)
        format.html { redirect_to trip, notice: 'Trip was successfully updated.' }
        format.json { render :show, status: :ok, address: trip }
      else
        format.html { render :edit }
        format.json { render json: trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trips/1
  # DELETE /trips/1.json
  def destroy
    trip.destroy
    respond_to do |format|
      format.html { redirect_to trips_url, notice: 'Trip was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trip
      trip = Trip.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trip_params
      params.require(:trip).permit(
        :name,
        :description,
        :address,
        :date,
        :user_id,
        :longitude,
        :latitude)
    end

    def invite_params
      params.require(:invite).permit(:email, :name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
-# navigati%ul.nav.navbar-navon styled for Bootstrap 3.0
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Trips', trips_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        = render 'layouts/navigation_links'
      %ul.nav.navbar-nav.navbar-right
        = render 'layouts/session_links'

app/views/layouts/_session_links.html.haml
- if user_signed_in?
    / %li= link_to current_user.name
    %li= link_to 'Edit account', edit_user_registration_path
    %li= link_to 'Sign out', destroy_user_session_path, method: 'delete'
- else
    %li= link_to 'Sign in', new_user_session_path
    %li= link_to 'Sign up', new_user_registration_path

app/views/layouts/application.html.haml
= Gon::Base.render_data({})
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Placetravel'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Placetravel'}"}
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/navigation'
    %main{:role => "main"}
      = render 'layouts/messages'
      = yield

app/views/pages/about.html.haml
%h1 Pages#about
%p Find me in app/views/pages/about.html.haml

app/views/pages/home.html.haml
%p.background
  = image_tag("travel.png")

  %p.centerize
    = link_to 'Begin Your Travel here!', trips_path, class: 'btn btn-default'

app/views/places/_form.html.haml
= simple_form_for([trip, place]) do |f|
  = f.error_notification

  .form-inputs
    %h4 Name
    = f.input :name, label: false
    %h4 Address
    = f.input :address, label: false
    %h4 Description
    = f.input :description, label: false
    .container
      .row
        .col-md-2
          %h4 Price
          = f.input :price, label: false
        .col-md-1
        .col-md-2
          .form-actions.form-button-margin
            = f.button :submit, class: 'btn btn-success'
        .col-md-7

app/views/places/edit.html.haml
.container.well
  .row
    .col-md-1
    .col-md-10
      %h1.header Edit place

      = render 'form'

      = link_to 'Show', trip_place_path(place.trip, place), class: 'btn btn-default'
      = link_to 'Back', trip_places_path(place.trip), class: 'btn btn-default'
    .col-md-1

app/views/places/index.html.haml
%script{src: "//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry", type: "text/javascript"}
%script{src: '//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js', type: 'text/javascript'}

.container.well
  .row
    .col-md-1
    .col-md-10
      %h1.header= trip.name
    .col-md-1
  .row
    .col-md-12
      %table.table.table-hover
        %thead
          %tr
            %th Name
            %th Address
            %th Description
            %th Price
            %th
            %th
        %tbody
          - places.each do |place|
            %tr
              %td.trip_name
                =link_to place.name, trip_place_path(place.trip, place)
              %td= place.address
              %td= truncate("#{place.description}", length: 30, separator: ' ')
              %td= place.price
              %td.signature
                by
                = place.user
              %td.btn-group
                %span.action-buttons= link_to 'Edit', edit_trip_place_path(place.trip, place), class: 'btn btn-primary'
                %span.action-buttons= link_to 'Destroy', trip_place_path(place.trip, place), class: 'btn btn-danger', method: :delete, data: { :confirm => 'Are you sure?' }
  .row
    .col-md-2
    .col-md-8.map-margin
      - if places.count > 0
        #map.map
      - else
        There are no places. Why not add some?

      :javascript
        handler = Gmaps.build('Google');
        handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
          markers = handler.addMarkers( gon.hash );
          handler.bounds.extendWith(markers);
          handler.fitMapToBounds();
        });
    .col-md-2
  .row
    .col-md-2
    .col-md-10
      = link_to 'New Place', new_trip_place_path(trip), class: 'btn btn-success'
      = link_to 'Back', trips_path, class: 'btn btn-default'

app/views/places/new.html.haml
%h1 New place

= render 'form'

= link_to 'Back', trip_places_path(trip), class: 'btn btn-default'

app/views/places/show.html.haml
.container.well
  .row
    .col-md-1
    .col-md-10
      %p#notice= notice
      %h2.header= place.name
    .col-md-1
  .row
    .col-md-1
    .col-md-10.signature
      = "--created by #{place.user} in trip '#{place.trip.name}'"
    .col-md-1
  .row.address
    .col-md-1
    .col-md-6
      %b Address:
      = place.address
    .col-md-1
    .col-md-3
      %b Price:
      = place.price
    .col-md-1
  .row
    .col-md-1
    .col-md-10.well
      = place.description
    .col-md-1
  .row
    .col-md-1
    .col-md-10.button-margins
      = link_to 'Edit', edit_trip_place_path(place.trip, place), class: 'btn btn-primary'
      = link_to 'Back', trip_places_path(place.trip), class: 'btn btn-default'
    .col-md-1

app/views/trips/_form.html.haml
= simple_form_for(trip) do |f|
  = f.error_notification

  .form-inputs
    %h4 Trip name
    = f.input :name, label: false
    %h4 Description
    = f.input :description, label: false
    %h4 Address
    = f.input :address, label: false
    .container
      .row
        .col-md-3
          %h4 Date
          = f.input :date, label: false, as: :datetime_picker
        .col-md-1
        .col-md-2
          .form-actions.form-button-margin
            = f.button :submit, class: 'btn btn-success'
        .col-md-6

app/views/trips/edit.html.haml
.container.well
  .row
    .col-md-1
    .col-md-10
      %h1.header Edit trip

      = render 'form'

      = link_to 'Show', trip, class: 'btn btn-default'
      = link_to 'Back', trips_path, class: 'btn btn-default'
    .col-md-1

app/views/trips/index.html.haml
.container.well
  .row
    .col-md-1
    .col-md-10
      %h1.header Your trips
    .col-md-1
  .row
    .col-md-12
      %table.table
        %thead
          %tr
            %th
            %th Name
            %th Location
            %th Date
            %th Created by
            %th
          %tbody
            - trips.each do |trip|
              %tr
                %td
                  =link_to trip_users_path(trip) do
                    %span.badge.glyphicon.glyphicon-user= trip.users.count
                %td.centered.trip_name= link_to trip.name, trip_path(trip)
                %td.centered= trip.address
                %td.centered= trip.date
                %td.centered= trip.user
                %td.action-buttons
                  = link_to trip_places_path(trip) do
                    %span.btn.btn-default.btn-size
                      .margin
                        %span.badge.glyphicon.glyphicon-pushpin= trip.places.count
                        = trip.places_display
                %end
                - if trip.user == current_user
                  %td
                    .btn-group
                      %span.action-buttons= link_to 'Edit', edit_trip_path(trip), class: 'btn btn-primary'
                      %span.action-buttons= link_to 'Destroy', trip, class: 'btn btn-danger', method: :delete, data: { confirm: :'Are you sure?' }
  .row
    .col-md-12
    .col-md-10
      = link_to 'New Trip', new_trip_path, class: 'btn btn-success'

app/views/trips/new.html.haml
%h1 New trip

= render 'form'

= link_to 'Back', trips_path, class: 'btn btn-default'

app/views/trips/show.html.haml
%p#notice= notice

.container
  .row
    .col-md-1
    .col-md-10.well
      .row
        .col-md-1
        .col-md-10
          %h2.header
            = trip.name
        .col-md-1
      .row
        .col-md-1
        .col-md-10.well
          = trip.description
        .col-md-1
      .row
        .col-md-9
        .col-md-3
          .location
            = trip.address
      .row
        .col-md-9
        .col-md-3
          = trip.trip_date
      .row
        .col-md-9
        .col-md-3.signature
          = "by #{trip.user}"
      - if policy(trip).invite?
        .container
          .row
            .col-md-2
            .col-md-5
              %h4 Invite a friend:
              = simple_form_for :invite, { url: trip_invite_path(trip) } do |f|
                = f.input :email, label: false, placeholder: 'email@example.com'
                = f.input :name, label: false, placeholder: 'Name'
                = f.submit 'Invite!', class: 'btn btn-primary'
            .col-md-5
    .col-md-1

.container
  .row.button-margins
    .col-md-1
    .col-md-2
      = link_to 'Edit', edit_trip_path(trip), class: 'btn btn-primary'
      = link_to 'Back', trips_path, class: 'btn btn-default'
    .col-md-3
      - if policy(@membership).confirm?
        = link_to 'Accept', confirm_membership_path(@membership.id), class: 'btn btn-success'
    .col-md-6

app/views/trips/users.html.haml
.container
  .row
    .col-md-12
      .well
        %h1.header Trip members
        %h5.header= "-- #{trip.name}"
        %table.table
          %tr
            %th Name
            %th E-mail
          - trip.users.each do |user|
            %tr
              %td
                = user.name
              %td
                = user.email
        %p
          =link_to 'Back', trips_path, class: 'btn btn-default'